<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MGM.MediaServices.Worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MGM.MediaServices.Core\MGM.MediaServices.Core.csproj" />
  </ItemGroup>

</Project>
