<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MGM.MediaServices.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MGM.MediaServices.Core\MGM.MediaServices.Core.csproj" />
    <ProjectReference Include="..\MGM.MediaServices.Worker\MGM.MediaServices.Worker.csproj" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
